// Default exercise library. Each exercise: id, name, muscle, equipment.
const DEFAULT_EXERCISES = [
  // Chest
  { id: "barbell-bench-press", name: "Barbell bench press", muscle: "Chest", equipment: "Barbell" },
  { id: "incline-barbell-bench-press", name: "Incline barbell bench press", muscle: "Chest", equipment: "Barbell" },
  { id: "decline-barbell-bench-press", name: "Decline barbell bench press", muscle: "Chest", equipment: "Barbell" },
  { id: "smith-machine-bench-press", name: "Smith machine bench press", muscle: "Chest", equipment: "Machine" },
  { id: "dumbbell-bench-press", name: "Dumbbell bench press", muscle: "Chest", equipment: "Dumbbell" },
  { id: "incline-dumbbell-press", name: "Incline dumbbell press", muscle: "Chest", equipment: "Dumbbell" },
  { id: "decline-dumbbell-press", name: "Decline dumbbell press", muscle: "Chest", equipment: "Dumbbell" },
  { id: "dumbbell-fly", name: "Dumbbell fly", muscle: "Chest", equipment: "Dumbbell" },
  { id: "incline-dumbbell-fly", name: "Incline dumbbell fly", muscle: "Chest", equipment: "Dumbbell" },
  { id: "dumbbell-pullover", name: "Dumbbell pullover", muscle: "Chest", equipment: "Dumbbell" },
  { id: "cable-crossover", name: "Cable crossover", muscle: "Chest", equipment: "Cable" },
  { id: "incline-cable-fly", name: "Incline cable fly", muscle: "Chest", equipment: "Cable" },
  { id: "low-cable-fly", name: "Low-to-high cable fly", muscle: "Chest", equipment: "Cable" },
  { id: "pec-deck-fly", name: "Pec deck fly", muscle: "Chest", equipment: "Machine" },
  { id: "machine-chest-press", name: "Machine chest press", muscle: "Chest", equipment: "Machine" },
  { id: "landmine-chest-press", name: "Landmine chest press", muscle: "Chest", equipment: "Barbell" },
  { id: "push-up", name: "Push-up", muscle: "Chest", equipment: "Bodyweight" },
  { id: "incline-push-up", name: "Incline push-up", muscle: "Chest", equipment: "Bodyweight" },
  { id: "decline-push-up", name: "Decline push-up", muscle: "Chest", equipment: "Bodyweight" },
  { id: "chest-dip", name: "Chest dip", muscle: "Chest", equipment: "Bodyweight" },
  { id: "svend-press", name: "Svend press", muscle: "Chest", equipment: "Other" },

  // Back
  { id: "deadlift", name: "Deadlift", muscle: "Back", equipment: "Barbell" },
  { id: "sumo-deadlift", name: "Sumo deadlift", muscle: "Back", equipment: "Barbell" },
  { id: "deficit-deadlift", name: "Deficit deadlift", muscle: "Back", equipment: "Barbell" },
  { id: "rack-pull", name: "Rack pull", muscle: "Back", equipment: "Barbell" },
  { id: "trap-bar-deadlift", name: "Trap bar deadlift", muscle: "Back", equipment: "Barbell" },
  { id: "pull-up", name: "Pull-up", muscle: "Back", equipment: "Bodyweight" },
  { id: "wide-grip-pull-up", name: "Wide-grip pull-up", muscle: "Back", equipment: "Bodyweight" },
  { id: "neutral-grip-pull-up", name: "Neutral-grip pull-up", muscle: "Back", equipment: "Bodyweight" },
  { id: "chin-up", name: "Chin-up", muscle: "Back", equipment: "Bodyweight" },
  { id: "inverted-row", name: "Inverted row", muscle: "Back", equipment: "Bodyweight" },
  { id: "lat-pulldown", name: "Lat pulldown", muscle: "Back", equipment: "Cable" },
  { id: "single-arm-lat-pulldown", name: "Single-arm lat pulldown", muscle: "Back", equipment: "Cable" },
  { id: "straight-arm-pulldown", name: "Straight-arm pulldown", muscle: "Back", equipment: "Cable" },
  { id: "seated-cable-row", name: "Seated cable row", muscle: "Back", equipment: "Cable" },
  { id: "cable-pullover", name: "Cable pullover", muscle: "Back", equipment: "Cable" },
  { id: "face-pull", name: "Face pull", muscle: "Back", equipment: "Cable" },
  { id: "barbell-row", name: "Barbell row", muscle: "Back", equipment: "Barbell" },
  { id: "pendlay-row", name: "Pendlay row", muscle: "Back", equipment: "Barbell" },
  { id: "t-bar-row", name: "T-bar row", muscle: "Back", equipment: "Barbell" },
  { id: "meadows-row", name: "Meadows row", muscle: "Back", equipment: "Barbell" },
  { id: "dumbbell-row", name: "Dumbbell row", muscle: "Back", equipment: "Dumbbell" },
  { id: "single-arm-dumbbell-row", name: "Single-arm dumbbell row", muscle: "Back", equipment: "Dumbbell" },
  { id: "chest-supported-row", name: "Chest-supported row", muscle: "Back", equipment: "Dumbbell" },
  { id: "machine-row", name: "Machine row", muscle: "Back", equipment: "Machine" },
  { id: "good-morning", name: "Good morning", muscle: "Back", equipment: "Barbell" },
  { id: "hyperextension", name: "Hyperextension", muscle: "Back", equipment: "Bodyweight" },
  { id: "band-pull-apart", name: "Band pull-apart", muscle: "Back", equipment: "Band" },

  // Shoulders
  { id: "overhead-press", name: "Overhead press", muscle: "Shoulders", equipment: "Barbell" },
  { id: "push-press", name: "Push press", muscle: "Shoulders", equipment: "Barbell" },
  { id: "upright-row", name: "Barbell upright row", muscle: "Shoulders", equipment: "Barbell" },
  { id: "landmine-press", name: "Landmine press", muscle: "Shoulders", equipment: "Barbell" },
  { id: "dumbbell-shoulder-press", name: "Dumbbell shoulder press", muscle: "Shoulders", equipment: "Dumbbell" },
  { id: "seated-dumbbell-press", name: "Seated dumbbell press", muscle: "Shoulders", equipment: "Dumbbell" },
  { id: "arnold-press", name: "Arnold press", muscle: "Shoulders", equipment: "Dumbbell" },
  { id: "lateral-raise", name: "Lateral raise", muscle: "Shoulders", equipment: "Dumbbell" },
  { id: "front-raise", name: "Front raise", muscle: "Shoulders", equipment: "Dumbbell" },
  { id: "rear-delt-fly", name: "Rear delt fly", muscle: "Shoulders", equipment: "Dumbbell" },
  { id: "cuban-press", name: "Cuban press", muscle: "Shoulders", equipment: "Dumbbell" },
  { id: "cable-lateral-raise", name: "Cable lateral raise", muscle: "Shoulders", equipment: "Cable" },
  { id: "cable-front-raise", name: "Cable front raise", muscle: "Shoulders", equipment: "Cable" },
  { id: "machine-shoulder-press", name: "Machine shoulder press", muscle: "Shoulders", equipment: "Machine" },
  { id: "reverse-pec-deck", name: "Reverse pec deck", muscle: "Shoulders", equipment: "Machine" },
  { id: "plate-front-raise", name: "Plate front raise", muscle: "Shoulders", equipment: "Other" },
  { id: "band-lateral-raise", name: "Band lateral raise", muscle: "Shoulders", equipment: "Band" },
  { id: "shrug", name: "Barbell shrug", muscle: "Shoulders", equipment: "Barbell" },

  // Arms - biceps
  { id: "barbell-curl", name: "Barbell curl", muscle: "Biceps", equipment: "Barbell" },
  { id: "ez-bar-curl", name: "EZ-bar curl", muscle: "Biceps", equipment: "Barbell" },
  { id: "drag-curl", name: "Drag curl", muscle: "Biceps", equipment: "Barbell" },
  { id: "reverse-curl", name: "Reverse curl", muscle: "Biceps", equipment: "Barbell" },
  { id: "dumbbell-curl", name: "Dumbbell curl", muscle: "Biceps", equipment: "Dumbbell" },
  { id: "hammer-curl", name: "Hammer curl", muscle: "Biceps", equipment: "Dumbbell" },
  { id: "incline-dumbbell-curl", name: "Incline dumbbell curl", muscle: "Biceps", equipment: "Dumbbell" },
  { id: "concentration-curl", name: "Concentration curl", muscle: "Biceps", equipment: "Dumbbell" },
  { id: "spider-curl", name: "Spider curl", muscle: "Biceps", equipment: "Dumbbell" },
  { id: "preacher-curl", name: "Preacher curl", muscle: "Biceps", equipment: "Barbell" },
  { id: "cable-curl", name: "Cable curl", muscle: "Biceps", equipment: "Cable" },
  { id: "cable-hammer-curl", name: "Cable hammer curl", muscle: "Biceps", equipment: "Cable" },
  { id: "band-curl", name: "Band curl", muscle: "Biceps", equipment: "Band" },

  // Arms - triceps
  { id: "close-grip-bench-press", name: "Close-grip bench press", muscle: "Triceps", equipment: "Barbell" },
  { id: "skull-crusher", name: "Skull crusher", muscle: "Triceps", equipment: "Barbell" },
  { id: "jm-press", name: "JM press", muscle: "Triceps", equipment: "Barbell" },
  { id: "triceps-pushdown", name: "Triceps pushdown", muscle: "Triceps", equipment: "Cable" },
  { id: "rope-pushdown", name: "Rope pushdown", muscle: "Triceps", equipment: "Cable" },
  { id: "overhead-cable-extension", name: "Overhead cable extension", muscle: "Triceps", equipment: "Cable" },
  { id: "overhead-triceps-extension", name: "Overhead triceps extension", muscle: "Triceps", equipment: "Dumbbell" },
  { id: "single-arm-overhead-extension", name: "Single-arm overhead extension", muscle: "Triceps", equipment: "Dumbbell" },
  { id: "dumbbell-kickback", name: "Dumbbell kickback", muscle: "Triceps", equipment: "Dumbbell" },
  { id: "machine-dip", name: "Machine dip", muscle: "Triceps", equipment: "Machine" },
  { id: "triceps-dip", name: "Triceps dip", muscle: "Triceps", equipment: "Bodyweight" },
  { id: "diamond-push-up", name: "Diamond push-up", muscle: "Triceps", equipment: "Bodyweight" },

  // Legs
  { id: "squat", name: "Barbell squat", muscle: "Legs", equipment: "Barbell" },
  { id: "front-squat", name: "Front squat", muscle: "Legs", equipment: "Barbell" },
  { id: "box-squat", name: "Box squat", muscle: "Legs", equipment: "Barbell" },
  { id: "zercher-squat", name: "Zercher squat", muscle: "Legs", equipment: "Barbell" },
  { id: "romanian-deadlift", name: "Romanian deadlift", muscle: "Legs", equipment: "Barbell" },
  { id: "hip-thrust", name: "Hip thrust", muscle: "Legs", equipment: "Barbell" },
  { id: "leg-press", name: "Leg press", muscle: "Legs", equipment: "Machine" },
  { id: "hack-squat", name: "Hack squat", muscle: "Legs", equipment: "Machine" },
  { id: "belt-squat", name: "Belt squat", muscle: "Legs", equipment: "Machine" },
  { id: "leg-extension", name: "Leg extension", muscle: "Legs", equipment: "Machine" },
  { id: "leg-curl", name: "Leg curl", muscle: "Legs", equipment: "Machine" },
  { id: "seated-leg-curl", name: "Seated leg curl", muscle: "Legs", equipment: "Machine" },
  { id: "goblet-squat", name: "Goblet squat", muscle: "Legs", equipment: "Dumbbell" },
  { id: "sumo-squat", name: "Sumo squat", muscle: "Legs", equipment: "Dumbbell" },
  { id: "walking-lunge", name: "Walking lunge", muscle: "Legs", equipment: "Dumbbell" },
  { id: "reverse-lunge", name: "Reverse lunge", muscle: "Legs", equipment: "Dumbbell" },
  { id: "step-up", name: "Step-up", muscle: "Legs", equipment: "Dumbbell" },
  { id: "bulgarian-split-squat", name: "Bulgarian split squat", muscle: "Legs", equipment: "Dumbbell" },
  { id: "pistol-squat", name: "Pistol squat", muscle: "Legs", equipment: "Bodyweight" },
  { id: "sissy-squat", name: "Sissy squat", muscle: "Legs", equipment: "Bodyweight" },

  // Glutes
  { id: "glute-bridge", name: "Glute bridge", muscle: "Glutes", equipment: "Bodyweight" },
  { id: "single-leg-hip-thrust", name: "Single-leg hip thrust", muscle: "Glutes", equipment: "Bodyweight" },
  { id: "cable-kickback", name: "Cable glute kickback", muscle: "Glutes", equipment: "Cable" },
  { id: "glute-kickback-machine", name: "Glute kickback machine", muscle: "Glutes", equipment: "Machine" },
  { id: "hip-abduction-machine", name: "Hip abduction machine", muscle: "Glutes", equipment: "Machine" },
  { id: "hip-adduction-machine", name: "Hip adduction machine", muscle: "Glutes", equipment: "Machine" },
  { id: "banded-lateral-walk", name: "Banded lateral walk", muscle: "Glutes", equipment: "Band" },

  // Calves
  { id: "calf-raise", name: "Standing calf raise", muscle: "Calves", equipment: "Machine" },
  { id: "seated-calf-raise", name: "Seated calf raise", muscle: "Calves", equipment: "Machine" },
  { id: "leg-press-calf-raise", name: "Leg press calf raise", muscle: "Calves", equipment: "Machine" },
  { id: "donkey-calf-raise", name: "Donkey calf raise", muscle: "Calves", equipment: "Machine" },
  { id: "smith-machine-calf-raise", name: "Smith machine calf raise", muscle: "Calves", equipment: "Machine" },
  { id: "single-leg-calf-raise", name: "Single-leg calf raise", muscle: "Calves", equipment: "Bodyweight" },

  // Forearms
  { id: "wrist-curl", name: "Barbell wrist curl", muscle: "Forearms", equipment: "Barbell" },
  { id: "reverse-wrist-curl", name: "Reverse wrist curl", muscle: "Forearms", equipment: "Barbell" },
  { id: "farmers-carry", name: "Farmer's carry", muscle: "Forearms", equipment: "Dumbbell" },
  { id: "plate-pinch", name: "Plate pinch hold", muscle: "Forearms", equipment: "Other" },
  { id: "wrist-roller", name: "Wrist roller", muscle: "Forearms", equipment: "Other" },

  // Core
  { id: "plank", name: "Plank", muscle: "Core", equipment: "Bodyweight" },
  { id: "side-plank", name: "Side plank", muscle: "Core", equipment: "Bodyweight" },
  { id: "sit-up", name: "Sit-up", muscle: "Core", equipment: "Bodyweight" },
  { id: "decline-sit-up", name: "Decline sit-up", muscle: "Core", equipment: "Bodyweight" },
  { id: "crunch", name: "Crunch", muscle: "Core", equipment: "Bodyweight" },
  { id: "bicycle-crunch", name: "Bicycle crunch", muscle: "Core", equipment: "Bodyweight" },
  { id: "v-up", name: "V-up", muscle: "Core", equipment: "Bodyweight" },
  { id: "mountain-climber", name: "Mountain climber", muscle: "Core", equipment: "Bodyweight" },
  { id: "dead-bug", name: "Dead bug", muscle: "Core", equipment: "Bodyweight" },
  { id: "hanging-leg-raise", name: "Hanging leg raise", muscle: "Core", equipment: "Bodyweight" },
  { id: "toes-to-bar", name: "Toes to bar", muscle: "Core", equipment: "Bodyweight" },
  { id: "russian-twist", name: "Russian twist", muscle: "Core", equipment: "Bodyweight" },
  { id: "ab-wheel-rollout", name: "Ab wheel rollout", muscle: "Core", equipment: "Other" },
  { id: "cable-crunch", name: "Cable crunch", muscle: "Core", equipment: "Cable" },
  { id: "pallof-press", name: "Pallof press", muscle: "Core", equipment: "Cable" },
  { id: "weighted-crunch-machine", name: "Weighted crunch machine", muscle: "Core", equipment: "Machine" },

  // Full Body / Olympic
  { id: "power-clean", name: "Power clean", muscle: "Full Body", equipment: "Barbell" },
  { id: "clean-and-jerk", name: "Clean and jerk", muscle: "Full Body", equipment: "Barbell" },
  { id: "snatch", name: "Snatch", muscle: "Full Body", equipment: "Barbell" },
  { id: "thruster", name: "Thruster", muscle: "Full Body", equipment: "Barbell" },
  { id: "kettlebell-swing", name: "Kettlebell swing", muscle: "Full Body", equipment: "Kettlebell" },
  { id: "kettlebell-front-rack-carry", name: "Kettlebell front rack carry", muscle: "Full Body", equipment: "Kettlebell" },
  { id: "turkish-get-up", name: "Turkish get-up", muscle: "Full Body", equipment: "Kettlebell" },
  { id: "burpee", name: "Burpee", muscle: "Full Body", equipment: "Bodyweight" },
  { id: "box-jump", name: "Box jump", muscle: "Full Body", equipment: "Bodyweight" },
  { id: "battle-ropes", name: "Battle ropes", muscle: "Full Body", equipment: "Other" },
];
